app = "artale-market-bot"
primary_region = "nrt"  # 東京區域，延遲較低

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHON_VERSION = "3.11"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[experimental]
  auto_rollback = true 